CFLAGS = -Wall -fpic -coverage -lm

default: playdom player unittest1 unittest2 unittest3 unittest4 cardtest1 cardtest2 cardtest3 cardtest4

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)
	
unittest1: unittest1.c dominion.o rngs.o
		gcc -o unittest1 -g  unittest1.c dominion.o rngs.o $(CFLAGS)

unittest2: unittest2.c dominion.o rngs.o
		gcc -o unittest2 -g  unittest2.c dominion.o rngs.o $(CFLAGS)
		
unittest3: unittest3.c dominion.o rngs.o
		gcc -o unittest3 -g  unittest3.c dominion.o rngs.o $(CFLAGS)
		
unittest4: unittest4.c dominion.o rngs.o
		gcc -o unittest4 -g  unittest4.c dominion.o rngs.o $(CFLAGS)
		
cardtest1: cardtest1.c dominion.o rngs.o
		gcc -o cardtest1 -g  cardtest1.c dominion.o rngs.o $(CFLAGS)
		
cardtest2: cardtest2.c dominion.o rngs.o
		gcc -o cardtest2 -g  cardtest2.c dominion.o rngs.o $(CFLAGS)
		
cardtest3: cardtest3.c dominion.o rngs.o
		gcc -o cardtest3 -g  cardtest3.c dominion.o rngs.o $(CFLAGS)
		
cardtest4: cardtest4.c dominion.o rngs.o
		gcc -o cardtest4 -g  cardtest4.c dominion.o rngs.o $(CFLAGS)

unittestresults.out: unittest1 unittest2 unittest3 unittest4 cardtest1 cardtest2 cardtest3 cardtest4
	echo "unittest1.c:" >> unittestresults.out
	unittest1 >> unittestresults.out
	gcov unittest1.c >> unittestresults.out
	
	echo "unittest2.c:" >> unittestresults.out
	unittest2 >> unittestresults.out
	gcov unittest1.c >> unittestresults.out
	
	echo "unittest3.c:" >> unittestresults.out
	unittest3 >> unittestresults.out
	gcov unittest3.c >> unittestresults.out
	
	echo "unittest4.c:" >> unittestresults.out
	unittest4 >> unittestresults.out
	gcov unittest4.c >> unittestresults.out
	
	echo "cardtest1.c:" >> unittestresults.out
	cardtest1 >> unittestresults.out
	gcov cardtest1.c >> unittestresults.out
	
	echo "cardtest2.c:" >> unittestresults.out
	cardtest2 >> unittestresults.out
	gcov cardtest2.c >> unittestresults.out
	
	echo "cardtest3.c:" >> unittestresults.out
	cardtest3 >> unittestresults.out
	gcov cardtest3.c >> unittestresults.out
	
	echo "cardtest4.c:" >> unittestresults.out
	cardtest4 >> unittestresults.out
	gcov cardtest4.c >> unittestresults.out
	
clean:
	rm unittestresults.out

cleanall:
	rm -f *.o playdom player unittest1 unittest2 unittest3 unittest4 cardtest1 cardtest2 cardtest3 cardtest4 *.exe *.gcov *.gcda *.gcno *.out
